
[overlay]
	#Whether to enable the overlay. If disabled, all other overlay options will be ignored.
	enableOverlay = true
	#The layout style of the overlay. 0: none, 1: above hot bar long, 2: above hot bar short, 3: top left, 4: top right, 5: bottom left, 6: bottom right
	#Range: 0 ~ 6
	overlayLayoutStyle = 1
	#The scale of the overlay text.
	#Range: 0.1 ~ 10.0
	overlayTextScale = 1.0
	#The color of the health bar when the player is not affected by any status effect. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthColorNormal = -47803
	#The color of the health bar when the player is poisoned. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthColorPoison = -6520798
	#The color of the health bar when the player is withered. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthColorWither = -11589849
	#The color of the health bar when the player is frozen. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthColorFrozen = -13133580
	#The color of the health bar bound. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthBoundColor = -10663864
	#The color of the health bar bound when the health rate is lower than the low health rate. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthBoundColorBlink = -1
	#The color of the health bar bound when the health rate is lower than the low health rate. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthBoundColorLow = -65536
	#The color of the empty part of the health bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthEmptyColor = -12171706
	#The color of the absorption bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	absorptionColor = -1715364
	#The color of the absorption bar bound. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	absorptionBoundColor = -1715364
	#The color of the food level bar when the player is not affected by any status effect. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	foodColorNormal = -724404
	#The color of the food level bar when the player is hungry. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	foodColorHunger = -5194156
	#The color of the food level bar bound. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	foodBoundColor = -9805502
	#The color of the food level bar bound when the food level is lower than the low food level. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	foodBoundColorBlink = -7437475
	#The color of the empty part of the food level bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	foodEmptyColor = -12171706
	#The color of the saturation bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	saturationColor = -367
	#The color of the experience bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	experienceColor = -7945129
	#The color of the experience bar bound. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	experienceBoundColor = -16183284
	#The color of the empty part of the experience bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	experienceEmptyColor = -14076625
	#The color of the air bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	airColor = -3019777
	#The color of the air bar bound. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	airBoundColor = -16739073
	#The color of the mount health bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	mountHealthColor = -2464212
	#The color of the mount health bar when the mount is not tamed. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	mountHealthColor2 = -4079167
	#The color of the mount health bar bound. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	mountHealthBoundColor = -8439527
	#The color of the mount health bar bound when the mount is not tamed. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	mountHealthBoundColor2 = -8816263
	#The color of the empty part of the mount health bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	mountHealthEmptyColor = -12171706
	#The color of the armor bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	armorColor = -1644558
	#The color of the armor bar bound. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	armorBoundColor = -13487566
	#The color of the empty part of the armor bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	armorEmptyColor = -12171706
	#The color of the armor toughness bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	armorToughnessColor = -9056769
	#Whether to enable health bar blink. This feature is designed to simulate the vanilla health icon blink.
	enableHealthBlink = true
	#The health bar will start to flash when health rate is lower than this value. From 0.0-1.0. 0.0 means never flash.
	#Range: 0.0 ~ 1.0
	lowHealthRate = 0.2
	#Whether to overwrite vanilla armor bar. If you don't like the mod's armor bar, you can disable this option.
	overwriteVanillaArmorBar = true
	#Whether to overwrite vanilla experience bar. If you don't like the mod's experience bar, you can disable this option, progress label won't be affected.
	overwriteVanillaExperienceBar = true
	#Whether to display experience progress on the side of the experience bar.
	displayExperienceProgress = true
	#Whether to display experience level on the experience bar.
	displayExperienceLevel = true
	#Whether to display health text.
	displayHealthText = true
	#0: Absorption will be displayed together with health bar. 1: Absorption will be displayed half transparently on the health bar. 2: Absorption will be displayed as bounds. Note: Since the absorption value can be higher than the max health, an extra number will be displayed to indicate value of absorption/max health, you can turn it off by editing 'displayAbsorptionDivMaxHealth'.
	#Range: 0 ~ 2
	displayAbsorptionMethod = 2
	#Whether to display the value of (absorption / max health). To avoid ambiguity, turn it to true if you hide the health text and don't display absorption bar together with health bar, or you may not be able to get correct absorption value.
	displayAbsorptionDivMaxHealth = false
	#0: Absorption text will be displayed together with health text. for example: 15(+10)/20. 1: Absorption text will be displayed separately. for example: 10 15/20. Note: if 'displayHealthText' is false, absorption text will be disabled.
	#Range: 0 ~ 1
	displayAbsorptionTextMethod = 1
	#Whether to enable food level bar blink. This feature is designed to simulate the vanilla food icon shake.
	enableFoodBlink = true
	#Whether to display saturation bar.
	displaySaturation = true
	#Whether to display exhaustion bar.
	displayExhaustion = true
	#Whether to display armor toughness bar.
	displayArmorToughness = true
	#The length of the bars if using corner layout. Affected bars: health, food, experience.
	#Range: 40 ~ 182
	cornerBarLength = 120
	#The horizontal padding of the bars if using corner layout.
	#Range: 0 ~ 100
	cornerHorizontalPadding = 16
	#The vertical padding of the bars if using corner layout.
	#Range: 0 ~ 100
	cornerVerticalPadding = 16

[entity]
	#Whether to enable health bar for entity. If disabled, all other health bar options will be ignored.
	enableHealthBar = false
	#The maximum distance to display mob health bar.
	#Range: 0.0 ~ 100.0
	maxDistance = 32.0
	#Whether to display health bar on players.
	showOnPlayers = true
	#Whether to display health bar on bosses.
	showOnBosses = true
	#Whether to display health bar on mobs with full health if the mob's absorption value is 0.
	showOnFullHealthWithoutAbsorption = true
	#Whether to display health bar on mobs with full health if the mob's absorption value is not 0.
	showOnFullHealthWithAbsorption = true
	#The half width of the health bar.
	#Range: 1 ~ 1000
	healthBarHalfWidth = 50
	#The half height of the health bar.
	#Range: 1 ~ 200
	healthBarHalfHeight = 3
	#The offset of the health bar on the Y axis.
	#Range: -10.0 ~ 10.0
	healthBarOffsetY = 0.2
	#The scale of the health bar.
	#Range: 0.001 ~ 0.1
	healthBarScale = 0.015
	#The scale of the health bar text.
	#Range: 0.1 ~ 1.0
	healthBarTextScale = 0.8
	#The offset of the health bar text on the Y axis.
	#Range: -10.0 ~ 10.0
	healthBarTextOffsetY = -2.75
	#The width of the health bar bound. 0 to 10. Hint: This value is a little hard to adjust. If you want to make the bounds looks thinner, you can increase the health bar width&height and decrease the health bar scale. You may also need to change the text scale and offset. This can be complicated, I highly recommend you to use some in-game config mod like 'configured'.
	#Range: 0 ~ 10
	healthBarBoundWidth = 2
	#Whether to render the vertex of the health bar bound.
	healthBarBoundVertex = false
	#The color of the health bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthBarHealthColor = -1442807808
	#The color of the absorption bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthBarAbsorptionColor = -1426063616
	#The color of the health bar bound. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthBarBoundColor = 1426063360
	#The color of the empty part of the health bar. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthBarEmptyColor = 855638016
	#Whether to use dynamic color for health bar. The color will be picked between healthBarHealthColorFull and healthBarHealthColorEmpty based on the health rate. If disabled, the health bar will always be healthBarHealthColor
	healthBarHealthColorDynamic = true
	#The color of the health bar when the mob is full health. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthBarHealthColorFull = -1442807808
	#The color of the health bar when the mob is low health. 0x00000000 to 0xFFFFFFFF. ARGB format.
	#Range: > -2147483648
	healthBarHealthColorEmpty = -1434451968

[hook]
	#Whether to hook Tough As Nails mod.
	toughAsNails = true
	#Whether to hook Thirst mod.
	thirstWasTaken = true
	#Whether to hook Mekanism mod.
	mekanism = true
	#Whether to hook Dehydration mod.
	dehydration = true

